package models

// APITypes lists zero values of every struct in this package that crosses
// the HTTP API boundary. cmd/genapi reflects over these to emit TypeScript
// interfaces in web/src/lib/api/generated/models.ts, so keep the list in
// sync when adding or removing API-bound structs.
func APITypes() []any {
	return []any{
		APIKey{},
		APIKeyCreated{},
		AltchaPublic{},
		AltchaWidgetPublic{},
		AuditEntry{},
		AuditPage{},
		AuthMethods{},
		AuthSettings{},
		AuthorInfo{},
		AudiobookTrack{},
		Book{},
		BookPage{},
		BookRating{},
		BookUpdate{},
		Bookmark{},
		Chapter{},
		Collection{},
		ComicManifest{},
		ComicPage{},
		ConvertResult{},
		FeedToken{},
		GuestCredentials{},
		Highlight{},
		InviteCreateResult{},
		InviteMeta{},
		InvitePublic{},
		KosyncDocument{},
		Library{},
		LibraryCreate{},
		LibraryS3Input{},
		LibraryS3Public{},
		LibraryStats{},
		LoginChallenge{},
		MetadataApplyRequest{},
		MetadataMatch{},
		MetadataProvider{},
		MetadataSearchQuery{},
		MetadataSearchResult{},
		MobiSection{},
		OIDCConfig{},
		OIDCDiscovery{},
		OfflineGrants{},
		PasswordPolicy{},
		PocketIDSettingsPublic{},
		Progress{},
		ReaderPrefs{},
		ReadingSession{},
		ReadingStats{},
		SMTPSettingsPublic{},
		ScanStatus{},
		SeriesInfo{},
		ServerConfigPublic{},
		ShareLink{},
		ShareLinkMeta{},
		SmartQuery{},
		TTSJob{},
		TTSSettingsPublic{},
		TTSStatus{},
		TTSUserPrefs{},
		Tag{},
		UploadSession{},
		UserPublic{},
		UserSession{},
		WebhookDelivery{},
		WebhookPublic{},
	}
}
