// Command genapi writes OpenAPI JSON and a typed TypeScript path client
// from the server API documentation. Run via: task generate
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"athenaeum/internal/server"
)

func main() {
	root := flag.String("root", ".", "repository root")
	check := flag.Bool("check", false, "exit non-zero if generated files would change")
	flag.Parse()

	spec := server.BuildOpenAPI()
	openapiPath := filepath.Join(*root, "web/src/lib/api/generated/openapi.json")
	tsPath := filepath.Join(*root, "web/src/lib/api/generated/paths.ts")

	openapiBytes, err := json.MarshalIndent(spec, "", "  ")
	if err != nil {
		fail(err)
	}
	openapiBytes = append(openapiBytes, '\n')

	tsBytes := []byte(renderTypeScript(spec))

	if *check {
		if err := checkFile(openapiPath, openapiBytes); err != nil {
			fail(err)
		}
		if err := checkFile(tsPath, tsBytes); err != nil {
			fail(err)
		}
		fmt.Println("generated API client is up to date")
		return
	}

	if err := os.MkdirAll(filepath.Dir(tsPath), 0o755); err != nil { // #nosec G301 -- generated sources in repo tree
		fail(err)
	}
	if err := os.WriteFile(openapiPath, openapiBytes, 0o644); err != nil { // #nosec G306 -- generated sources in repo tree
		fail(err)
	}
	if err := os.WriteFile(tsPath, tsBytes, 0o644); err != nil { // #nosec G306 -- generated sources in repo tree
		fail(err)
	}
	fmt.Printf("wrote %s\n", openapiPath)
	fmt.Printf("wrote %s\n", tsPath)
}

func checkFile(path string, want []byte) error {
	got, err := os.ReadFile(path) // #nosec G304 -- fixed generated paths under -root
	if err != nil {
		return fmt.Errorf("%s missing (run task generate): %w", path, err)
	}
	if !bytes.Equal(got, want) {
		return fmt.Errorf("%s is stale (run task generate)", path)
	}
	return nil
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}

type opRef struct {
	ID      string
	Method  string
	Path    string
	Summary string
}

func renderTypeScript(spec server.OpenAPIExport) string {
	var ops []opRef
	paths := make([]string, 0, len(spec.Paths))
	for p := range spec.Paths {
		paths = append(paths, p)
	}
	sort.Strings(paths)
	for _, p := range paths {
		methods := make([]string, 0, len(spec.Paths[p]))
		for m := range spec.Paths[p] {
			methods = append(methods, m)
		}
		sort.Strings(methods)
		for _, m := range methods {
			op := spec.Paths[p][m]
			ops = append(ops, opRef{
				ID:      op.OperationID,
				Method:  strings.ToUpper(m),
				Path:    p,
				Summary: op.Summary,
			})
		}
	}
	sort.Slice(ops, func(i, j int) bool {
		if ops[i].Path == ops[j].Path {
			return ops[i].Method < ops[j].Method
		}
		return ops[i].Path < ops[j].Path
	})

	var b strings.Builder
	b.WriteString("// Code generated by genapi. DO NOT EDIT.\n")
	b.WriteString("// Regenerate with: task generate\n\n")
	b.WriteString("export type HttpMethod = \"GET\" | \"POST\" | \"PUT\" | \"PATCH\" | \"DELETE\" | \"HEAD\" | \"OPTIONS\";\n\n")
	b.WriteString("export type ApiOperation = {\n")
	b.WriteString("  readonly id: string;\n")
	b.WriteString("  readonly method: HttpMethod;\n")
	b.WriteString("  readonly path: string;\n")
	b.WriteString("  readonly summary: string;\n")
	b.WriteString("};\n\n")
	b.WriteString("export const apiOperations = [\n")
	for _, op := range ops {
		b.WriteString(fmt.Sprintf(
			"  { id: %q, method: %q, path: %q, summary: %q },\n",
			op.ID, op.Method, op.Path, op.Summary,
		))
	}
	b.WriteString("] as const satisfies readonly ApiOperation[];\n\n")
	b.WriteString("export type ApiPath = (typeof apiOperations)[number][\"path\"];\n")
	b.WriteString("export type ApiOperationId = (typeof apiOperations)[number][\"id\"];\n\n")
	b.WriteString("const byId = Object.fromEntries(apiOperations.map((op) => [op.id, op])) as Record<\n")
	b.WriteString("  ApiOperationId,\n")
	b.WriteString("  (typeof apiOperations)[number]\n")
	b.WriteString(">;\n\n")
	b.WriteString("/** Look up a generated operation by OpenAPI operationId. */\n")
	b.WriteString("export function apiOp(id: ApiOperationId): (typeof apiOperations)[number] {\n")
	b.WriteString("  return byId[id];\n")
	b.WriteString("}\n\n")
	b.WriteString("/** Replace `{param}` segments in a generated path template. */\n")
	b.WriteString("export function apiPath(template: ApiPath, params: Record<string, string | number> = {}): string {\n")
	b.WriteString("  return template.replace(/\\{([^}]+)\\}/g, (_, name: string) => {\n")
	b.WriteString("    const value = params[name];\n")
	b.WriteString("    if (value === undefined || value === null) {\n")
	b.WriteString("      throw new Error(`missing path param ${name} for ${template}`);\n")
	b.WriteString("    }\n")
	b.WriteString("    return encodeURIComponent(String(value));\n")
	b.WriteString("  });\n")
	b.WriteString("}\n")
	return b.String()
}
