package main

import (
	"fmt"
	"os"
	"reflect"
	"sort"
	"strings"
	"time"

	"athenaeum/internal/i18n"
	"athenaeum/internal/library"
	"athenaeum/internal/models"
	"athenaeum/internal/server"
	"athenaeum/internal/system"
	"athenaeum/internal/telemetry"
)

var timeType = reflect.TypeOf(time.Time{})

// tsRenames maps Go types whose API-facing TypeScript name differs from the
// Go struct name, usually because the Go type is a masked "Public" view.
var tsRenames = map[reflect.Type]string{
	reflect.TypeOf(models.UserPublic{}):         "User",
	reflect.TypeOf(models.InvitePublic{}):       "Invite",
	reflect.TypeOf(models.WebhookPublic{}):      "Webhook",
	reflect.TypeOf(models.ServerConfigPublic{}): "ServerConfig",
	reflect.TypeOf(models.Library{}):            "LibraryMount",
	reflect.TypeOf(models.LibraryS3Public{}):    "LibraryS3Config",
	reflect.TypeOf(models.LibraryCreate{}):      "LibraryCreateInput",
	reflect.TypeOf(system.Stats{}):              "SystemStats",
	reflect.TypeOf(telemetry.PublicConfig{}):    "TelemetryConfig",
	reflect.TypeOf(i18n.LocaleInfo{}):           "I18nLocaleInfo",
	reflect.TypeOf(i18n.Catalog{}):              "I18nCatalog",
}

// apiModelTypes returns every struct reflected into generated/models.ts:
// the registry in internal/models plus API-bound types living elsewhere.
func apiModelTypes() []reflect.Type {
	var out []reflect.Type
	for _, v := range models.APITypes() {
		out = append(out, reflect.TypeOf(v))
	}
	for _, v := range []any{
		i18n.Catalog{},
		i18n.LocaleInfo{},
		library.FSBrowseResult{},
		library.FSDirEntry{},
		library.IntegrityReport{},
		library.MaintenanceStatus{},
		library.MetadataAutoMatchRequest{},
		library.MetadataMatchStatus{},
		library.MissingBook{},
		server.APIDoc{},
		server.APIDocEndpoint{},
		server.APIDocSection{},
		system.DiskUsage{},
		system.Stats{},
		telemetry.PublicConfig{},
	} {
		out = append(out, reflect.TypeOf(v))
	}
	return out
}

func renderModels() string {
	registry := make(map[reflect.Type]string)
	for _, t := range apiModelTypes() {
		name := t.Name()
		if renamed, ok := tsRenames[t]; ok {
			name = renamed
		}
		if prev, dup := registry[t]; dup && prev != name {
			fmt.Fprintf(os.Stderr, "genapi: duplicate registration of %s\n", t)
			continue
		}
		registry[t] = name
	}

	names := make([]string, 0, len(registry))
	byName := make(map[string]reflect.Type, len(registry))
	for t, name := range registry {
		if _, dup := byName[name]; dup {
			fmt.Fprintf(os.Stderr, "genapi: name collision for %s (%s)\n", name, t)
			continue
		}
		byName[name] = t
		names = append(names, name)
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("// Code generated by genapi. DO NOT EDIT.\n")
	b.WriteString("// Regenerate with: task generate\n\n")
	b.WriteString("// Interfaces mirrored from Go API models (internal/models and friends).\n\n")
	for _, name := range names {
		writeInterface(&b, byName[name], name, registry)
	}
	return b.String()
}

func writeInterface(b *strings.Builder, t reflect.Type, name string, registry map[reflect.Type]string) {
	var extends []string
	var fields strings.Builder
	writeFields(&fields, t, registry, &extends)
	b.WriteString("export interface ")
	b.WriteString(name)
	if len(extends) > 0 {
		sort.Strings(extends)
		b.WriteString(" extends ")
		b.WriteString(strings.Join(extends, ", "))
	}
	b.WriteString(" {\n")
	b.WriteString(fields.String())
	b.WriteString("}\n\n")
}

// writeFields emits one line per serialized field, flattening embedded
// structs the way encoding/json does. Embedded structs that are themselves
// registered API models are emitted via `extends` instead.
func writeFields(out *strings.Builder, t reflect.Type, registry map[reflect.Type]string, extends *[]string) {
	for i := 0; i < t.NumField(); i++ {
		f := t.Field(i)
		if f.PkgPath != "" {
			continue // unexported, encoding/json skips it
		}
		jsonName, omitempty, skip := parseJSONTag(f)
		if skip {
			continue
		}
		ft := f.Type
		if f.Anonymous && jsonName == "" {
			base := ft
			if base.Kind() == reflect.Pointer {
				base = base.Elem()
			}
			if base.Kind() == reflect.Struct && base != timeType {
				if ref, ok := registry[base]; ok {
					*extends = append(*extends, ref)
				} else {
					writeFields(out, base, registry, extends)
				}
				continue
			}
		}
		if jsonName == "" {
			jsonName = f.Name
		}
		optional := omitempty
		ts := tsType(ft, registry)
		if ft.Kind() == reflect.Pointer && !omitempty {
			ts += " | null"
		}
		out.WriteString("  ")
		out.WriteString(jsonName)
		if optional {
			out.WriteString("?")
		}
		out.WriteString(": ")
		out.WriteString(ts)
		out.WriteString(";\n")
	}
}

func parseJSONTag(f reflect.StructField) (name string, omitempty, skip bool) {
	tag, ok := f.Tag.Lookup("json")
	if !ok {
		return "", false, false
	}
	parts := strings.Split(tag, ",")
	if parts[0] == "-" {
		return "", false, true
	}
	name = parts[0]
	for _, opt := range parts[1:] {
		if opt == "omitempty" {
			omitempty = true
		}
	}
	return name, omitempty, false
}

func tsType(t reflect.Type, registry map[reflect.Type]string) string {
	for t.Kind() == reflect.Pointer {
		t = t.Elem()
	}
	if t == timeType {
		return "string"
	}
	switch t.Kind() {
	case reflect.Bool:
		return "boolean"
	case reflect.String:
		return "string"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number"
	case reflect.Slice, reflect.Array:
		if t.Elem().Kind() == reflect.Uint8 {
			return "string" // []byte serializes as base64
		}
		elem := tsType(t.Elem(), registry)
		if strings.Contains(elem, " | ") {
			elem = "(" + elem + ")"
		}
		return elem + "[]"
	case reflect.Map:
		return "Record<string, " + tsType(t.Elem(), registry) + ">"
	case reflect.Struct:
		if name, ok := registry[t]; ok {
			return name
		}
		fmt.Fprintf(os.Stderr, "genapi: warning: unregistered struct %s rendered as unknown\n", t)
		return "unknown"
	case reflect.Interface:
		return "unknown"
	default:
		fmt.Fprintf(os.Stderr, "genapi: warning: unhandled kind %s for %s\n", t.Kind(), t)
		return "unknown"
	}
}
